# Generated by Django 3.1.4 on 2020-12-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_account_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='accounttransaction',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='user_id',
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transactions', to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default='88fe5979-2741-4e9b-90ba-b66444cce98c',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='user',
            field=models.ForeignKey(default='88fe5979-2741-4e9b-90ba-b66444cce98c',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='expenses',
                                    to='api.user'),
            preserve_default=False,
        ),
    ]
