# Generated by Django 3.1.4 on 2020-12-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_renamed_foreign_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='monthlyexpense',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'created'},
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_gross_income',
            field=models.IntegerField(default=0),
        ),
    ]
