# Generated by Django 3.1.4 on 2020-12-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_user_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_user_accounts'),
        ),
    ]
