# Generated by Django 3.1.4 on 2020-12-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_monthly_expense_backref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finished_registration',
            field=models.BooleanField(default=False),
        ),
    ]
